In [28]:
import numpy as np
arr=np.array([[1,2,3],[3,5,6],[7,8,9]])
result=arr+2
print(result)

[[ 3  4  5]
 [ 5  7  8]
 [ 9 10 11]]


In [29]:
import numpy as np 
arer = np.array([[-1, 2, 0, 4,0,1], [4, -0.5, 6, 0,0,1], [2.6, 0, 7, 8,0,1], [3, -7, 4, 2.0,0,1]]) 
arr2 = arer[:2, ::3] 
print ("first 2 rows and alternate columns(0 and 2):\n", arr2) 
print ("*************************************** ")
arer.shape

first 2 rows and alternate columns(0 and 2):
 [[-1.  4.]
 [ 4.  0.]]
*************************************** 


(4, 6)

In [6]:
a = np.array([[1, 2], [3, 4]]) 
print ("Adding 1 to every element:", a + 1)

Adding 1 to every element: [[2 3]
 [4 5]]


In [9]:
arr.shape

(3, 3)

In [2]:
import numpy as np
a = np.array([[25, 9], [36, 4]])
b = np.array([[1, 2], [3, 8]])
print ("\nSum of all array elements: ", a.sum())
print ("*************************************** ")
Sqrt = np.sqrt(a) 
print(Sqrt)
print ("*************************************** ")
Sum = np.add(a, b) 
print(Sum) 



Sum of all array elements:  74
*************************************** 
[[5. 3.]
 [6. 2.]]
*************************************** 
[[26 11]
 [39 12]]


In [3]:
Trans_arr = a.T 
print(Trans_arr)

[[25 36]
 [ 9  4]]
